"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Award, Briefcase, Check, CircleUserRound, Code2, FolderKanban, GraduationCap, LayoutTemplate, Loader2, Plus, Save, Sparkles, Trash2 } from "lucide-react";
import { resumeSchema, type ResumeInput } from "@/lib/validation";
import { Field, TextArea } from "@/components/ui";
import { ResumePreview } from "./resume-preview";
import { PdfButton } from "./pdf-button";
import { cn } from "@/lib/utils";

const sections=[
  ["templates","Templates",LayoutTemplate],["personal","Personal info",CircleUserRound],["summary","Summary",Sparkles],["experience","Experience",Briefcase],["education","Education",GraduationCap],["skills","Skills",Code2],["projects","Projects",FolderKanban],["certifications","Certifications",Award]
] as const;
type Section=typeof sections[number][0];

export function ResumeEditor({id,initial}:{id:string;initial:ResumeInput}){
  const [active,setActive]=useState<Section>("templates"); const [status,setStatus]=useState<"idle"|"saving"|"saved"|"error">("idle"); const [message,setMessage]=useState("");
  const {register,handleSubmit,watch,setValue,formState:{errors}}=useForm<ResumeInput>({resolver:zodResolver(resumeSchema),defaultValues:initial,mode:"onBlur"});
  const data=watch();
  async function save(values:ResumeInput){setStatus("saving");setMessage("");try{const res=await fetch(`/api/resumes/${id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(values)});const json=await res.json();if(!res.ok)throw new Error(json.error);setStatus("saved");setTimeout(()=>setStatus("idle"),2500)}catch(e){setStatus("error");setMessage(e instanceof Error?e.message:"Unable to save")}}
  function add<K extends "experiences"|"educations"|"skills"|"projects"|"certifications">(key:K,value:ResumeInput[K][number]){setValue(key,[...data[key],value] as never,{shouldDirty:true})}
  function remove(key:"experiences"|"educations"|"skills"|"projects"|"certifications",i:number){setValue(key,data[key].filter((_,index)=>index!==i) as never,{shouldDirty:true})}
  return <div className="flex h-[calc(100vh-4rem)] min-h-[650px] overflow-hidden bg-[#efeee9]">
    <aside className="hidden w-52 shrink-0 border-r border-black/[.08] bg-white p-3 lg:block"><p className="px-3 pb-3 pt-2 text-[10px] font-bold uppercase tracking-widest text-black/35">Resume sections</p>{sections.map(([key,label,Icon])=><button key={key} onClick={()=>setActive(key)} className={cn("mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium",active===key?"bg-forge-50 text-forge-700":"text-black/55 hover:bg-black/[.03]")}><Icon size={17}/>{label}</button>)}</aside>
    <main className="flex min-w-0 flex-1 flex-col bg-white xl:max-w-xl"><div className="flex items-center gap-2 overflow-x-auto border-b border-black/[.07] px-4 py-2 lg:hidden">{sections.map(([key,label,Icon])=><button key={key} title={label} onClick={()=>setActive(key)} className={cn("shrink-0 rounded-lg p-2",active===key?"bg-forge-50 text-forge-700":"text-black/45")}><Icon size={18}/></button>)}</div>
      <form onSubmit={handleSubmit(save,()=>{setStatus("error");setMessage("Please fix the highlighted fields.")})} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 overflow-y-auto px-5 py-7 sm:px-8"><div className="mx-auto max-w-lg"><EditorSection active={active} register={register} errors={errors} data={data} setTemplate={template=>setValue("template",template,{shouldDirty:true})} add={add} remove={remove}/></div></div><div className="flex items-center justify-between border-t border-black/[.07] bg-white px-5 py-3"><span className={cn("text-xs",status==="error"?"text-red-600":"text-black/45")}>{status==="saved"?<span className="flex items-center gap-1"><Check size={14}/>Saved</span>:message}</span><button disabled={status==="saving"} className="btn-primary py-2">{status==="saving"?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>}Save changes</button></div></form>
    </main>
    <aside className="hidden min-w-0 flex-1 flex-col xl:flex"><div className="flex h-14 items-center justify-between border-b border-black/[.07] px-5"><div className="flex gap-1 rounded-xl bg-black/5 p-1"><button onClick={()=>setValue("template","classic")} className={cn("rounded-lg px-3 py-1.5 text-xs font-semibold",data.template==="classic"&&"bg-white shadow-sm")}>Classic</button><button onClick={()=>setValue("template","modern")} className={cn("rounded-lg px-3 py-1.5 text-xs font-semibold",data.template==="modern"&&"bg-white shadow-sm")}>Modern</button></div><PdfButton data={data}/></div><div className="flex-1 overflow-y-auto p-7"><div className="mx-auto aspect-[1/1.414] max-w-[720px] shadow-soft"><ResumePreview data={data} compact/></div></div></aside>
  </div>
}

type Props={active:Section;register:ReturnType<typeof useForm<ResumeInput>>["register"];errors:ReturnType<typeof useForm<ResumeInput>>["formState"]["errors"];data:ResumeInput;setTemplate:(template:"classic"|"modern")=>void;add:<K extends "experiences"|"educations"|"skills"|"projects"|"certifications">(k:K,v:ResumeInput[K][number])=>void;remove:(k:"experiences"|"educations"|"skills"|"projects"|"certifications",i:number)=>void};
function EditorSection({active,register,errors,data,setTemplate,add,remove}:Props){
  const title=sections.find(x=>x[0]===active)?.[1];
  return <><p className="text-xs font-bold uppercase tracking-widest text-forge-700">{active==="templates"?"Design":"Editing"}</p><h1 className="mt-1 font-serif text-3xl font-bold">{title}</h1><p className="mb-7 mt-2 text-sm text-black/50">{active==="templates"?"Choose a layout. Your content stays exactly the same.":"Keep it clear, specific, and easy to scan."}</p>
    {active==="templates"&&<TemplateChooser selected={data.template} onSelect={setTemplate}/>} 
    {active==="personal"&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Resume title" className="sm:col-span-2" {...register("title")} error={errors.title?.message}/><Field label="Full name *" className="sm:col-span-2" {...register("profile.fullName")} error={errors.profile?.fullName?.message}/><Field label="Email *" type="email" {...register("profile.email")} error={errors.profile?.email?.message}/><Field label="Phone" {...register("profile.phone")}/><Field label="Location" {...register("profile.location")}/><Field label="Website" {...register("profile.website")}/><Field label="LinkedIn" className="sm:col-span-2" {...register("profile.linkedIn")}/></div>}
    {active==="summary"&&<TextArea label="Professional summary" rows={8} placeholder="A concise overview of your strengths, experience, and goals…" {...register("summary")}/>} 
    {active==="experience"&&<Repeat items={data.experiences} label="Add experience" onAdd={()=>add("experiences",{company:"",position:"",location:"",startDate:"",endDate:"",current:false,details:""})} onRemove={i=>remove("experiences",i)}>{i=><div className="grid gap-3 sm:grid-cols-2"><Field label="Position *" {...register(`experiences.${i}.position`)} error={errors.experiences?.[i]?.position?.message}/><Field label="Company *" {...register(`experiences.${i}.company`)} error={errors.experiences?.[i]?.company?.message}/><Field label="Location" {...register(`experiences.${i}.location`)}/><Field label="Start date" placeholder="Jan 2023" {...register(`experiences.${i}.startDate`)}/><Field label="End date" placeholder="Present" {...register(`experiences.${i}.endDate`)}/><label className="flex items-end gap-2 pb-3 text-sm"><input type="checkbox" {...register(`experiences.${i}.current`)}/>Currently work here</label><TextArea className="sm:col-span-2" label="Highlights" placeholder="Describe impact and results…" {...register(`experiences.${i}.details`)}/></div>}</Repeat>}
    {active==="education"&&<Repeat items={data.educations} label="Add education" onAdd={()=>add("educations",{school:"",degree:"",field:"",startDate:"",endDate:"",details:""})} onRemove={i=>remove("educations",i)}>{i=><div className="grid gap-3 sm:grid-cols-2"><Field label="School *" {...register(`educations.${i}.school`)} error={errors.educations?.[i]?.school?.message}/><Field label="Degree *" {...register(`educations.${i}.degree`)} error={errors.educations?.[i]?.degree?.message}/><Field label="Field of study" {...register(`educations.${i}.field`)}/><Field label="Start date" {...register(`educations.${i}.startDate`)}/><Field label="End date" {...register(`educations.${i}.endDate`)}/><TextArea className="sm:col-span-2" label="Details" {...register(`educations.${i}.details`)}/></div>}</Repeat>}
    {active==="skills"&&<Repeat items={data.skills} label="Add skill" onAdd={()=>add("skills",{name:"",level:""})} onRemove={i=>remove("skills",i)}>{i=><div className="grid gap-3 sm:grid-cols-2"><Field label="Skill *" {...register(`skills.${i}.name`)} error={errors.skills?.[i]?.name?.message}/><Field label="Level" placeholder="Advanced" {...register(`skills.${i}.level`)}/></div>}</Repeat>}
    {active==="projects"&&<Repeat items={data.projects} label="Add project" onAdd={()=>add("projects",{name:"",description:"",url:"",technologies:""})} onRemove={i=>remove("projects",i)}>{i=><div className="grid gap-3 sm:grid-cols-2"><Field label="Project name *" {...register(`projects.${i}.name`)} error={errors.projects?.[i]?.name?.message}/><Field label="URL" {...register(`projects.${i}.url`)}/><Field className="sm:col-span-2" label="Technologies" {...register(`projects.${i}.technologies`)}/><TextArea className="sm:col-span-2" label="Description" {...register(`projects.${i}.description`)}/></div>}</Repeat>}
    {active==="certifications"&&<Repeat items={data.certifications} label="Add certification" onAdd={()=>add("certifications",{name:"",issuer:"",date:"",url:""})} onRemove={i=>remove("certifications",i)}>{i=><div className="grid gap-3 sm:grid-cols-2"><Field label="Certification *" {...register(`certifications.${i}.name`)} error={errors.certifications?.[i]?.name?.message}/><Field label="Issuer" {...register(`certifications.${i}.issuer`)}/><Field label="Date" {...register(`certifications.${i}.date`)}/><Field label="Credential URL" {...register(`certifications.${i}.url`)}/></div>}</Repeat>}
  </>;
}
function Repeat<T>({items,label,onAdd,onRemove,children}:{items:T[];label:string;onAdd:()=>void;onRemove:(i:number)=>void;children:(i:number)=>React.ReactNode}){return <div className="space-y-4">{items.map((_,i)=><div className="card relative p-4" key={i}><button type="button" onClick={()=>onRemove(i)} aria-label="Remove item" className="absolute right-3 top-3 z-10 rounded-lg p-2 text-black/35 hover:bg-red-50 hover:text-red-600"><Trash2 size={16}/></button><div className="pr-8">{children(i)}</div></div>)}<button type="button" onClick={onAdd} className="btn-secondary w-full border-dashed"><Plus size={16}/>{label}</button></div>}

function TemplateChooser({selected,onSelect}:{selected:"classic"|"modern";onSelect:(template:"classic"|"modern")=>void}){return <div className="grid gap-5 sm:grid-cols-2"><TemplateCard name="Classic" description="Clean, familiar, and ATS-friendly." selected={selected==="classic"} onClick={()=>onSelect("classic")}><div className="h-full border-t-4 border-ink bg-white p-4"><div className="h-2 w-3/5 bg-ink"/><div className="mt-2 h-1 w-full bg-black/15"/><div className="mt-6 h-1.5 w-1/3 bg-forge-600"/><div className="mt-2 space-y-1">{[1,2,3,4].map(x=><div key={x} className="h-1 bg-black/10"/>)}</div></div></TemplateCard><TemplateCard name="Modern Split" description="A simple two-column editorial layout." selected={selected==="modern"} onClick={()=>onSelect("modern")}><div className="grid h-full grid-cols-[38%_1fr] bg-white"><div className="bg-[#e2e7e3] p-3"><div className="h-2 w-4/5 bg-ink"/><div className="mt-4 space-y-1">{[1,2,3].map(x=><div key={x} className="h-1 bg-black/15"/>)}</div><div className="mt-6 h-1.5 w-2/3 bg-forge-700"/></div><div className="p-3"><div className="h-1.5 w-3/4 bg-forge-700"/><div className="mt-3 space-y-1">{[1,2,3,4,5].map(x=><div key={x} className="h-1 bg-black/10"/>)}</div></div></div></TemplateCard></div>}
function TemplateCard({name,description,selected,onClick,children}:{name:string;description:string;selected:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" onClick={onClick} className={cn("overflow-hidden rounded-2xl border-2 bg-white text-left transition hover:-translate-y-0.5 hover:shadow-soft",selected?"border-forge-600 ring-4 ring-forge-500/10":"border-black/10")}><div className="aspect-[1/1.25] bg-[#f5f4f0] p-5"><div className="h-full shadow-sm">{children}</div></div><div className="flex items-start justify-between border-t border-black/[.07] p-4"><div><div className="font-bold">{name}</div><p className="mt-1 text-xs leading-5 text-black/50">{description}</p></div>{selected&&<span className="grid size-6 shrink-0 place-items-center rounded-full bg-forge-600 text-white"><Check size={14}/></span>}</div></button>}
