import type { ResumeInput } from "@/lib/validation";
import { cn } from "@/lib/utils";

export function ResumePreview({ data, compact=false }: { data:ResumeInput; compact?:boolean }) {
  return data.template==="modern"?<ModernPreview data={data} compact={compact}/>:<ClassicPreview data={data} compact={compact}/>;
}

function ClassicPreview({data,compact}:{data:ResumeInput;compact:boolean}){const p=data.profile;return <div className={cn("min-h-full bg-white text-[#202521]",compact?"p-8 text-[8px]":"p-[7%] text-[11px]")}><header className="border-b-2 border-ink pb-4"><h1 className={cn("font-serif font-bold",compact?"text-2xl":"text-4xl")}>{p.fullName||"Your Name"}</h1><div className="mt-2 flex flex-wrap gap-x-3 text-black/55">{contact(p).map((x,i)=><span key={i}>{x}</span>)}</div></header>{data.summary&&<Section title="Professional Summary"><p className="whitespace-pre-line leading-relaxed">{data.summary}</p></Section>}<MainSections data={data}/><div className="grid grid-cols-2 gap-8"><Skills data={data}/><Certifications data={data}/></div></div>}

function ModernPreview({data,compact}:{data:ResumeInput;compact:boolean}){const p=data.profile;return <div className={cn("grid min-h-full grid-cols-[36%_64%] bg-white text-[#202521]",compact?"text-[8px]":"text-[11px]")}><aside className={cn("bg-[#e4e8e4]",compact?"p-6":"p-[12%]")}><h1 className={cn("font-serif font-bold uppercase leading-tight",compact?"text-xl":"text-3xl")}>{p.fullName||"Your Name"}</h1><div className="mt-5 space-y-2 break-words text-black/65">{contact(p).map((x,i)=><div key={i}>{x}</div>)}</div>{data.summary&&<ModernSection title="Summary"><p className="whitespace-pre-line leading-relaxed">{data.summary}</p></ModernSection>}<Skills data={data} modern/><Certifications data={data} modern/></aside><main className={cn(compact?"p-7":"p-[8%]")}><MainSections data={data} modern/></main></div>}

function MainSections({data,modern=false}:{data:ResumeInput;modern?:boolean}){const Wrapper=modern?ModernSection:Section;return <>{!!data.experiences.length&&<Wrapper title="Professional Experience">{data.experiences.map((x,i)=><Entry key={i} title={x.position} subtitle={x.company+(x.location?` · ${x.location}`:"")} date={`${x.startDate}${x.startDate||x.endDate?" — ":""}${x.current?"Present":x.endDate}`} details={x.details}/>)}</Wrapper>}{!!data.educations.length&&<Wrapper title="Education">{data.educations.map((x,i)=><Entry key={i} title={x.degree+(x.field?` in ${x.field}`:"")} subtitle={x.school} date={`${x.startDate}${x.startDate||x.endDate?" — ":""}${x.endDate}`} details={x.details}/>)}</Wrapper>}{!!data.projects.length&&<Wrapper title="Projects">{data.projects.map((x,i)=><Entry key={i} title={x.name} subtitle={x.technologies} date={x.url} details={x.description}/>)}</Wrapper>}</>}
function Skills({data,modern=false}:{data:ResumeInput;modern?:boolean}){if(!data.skills.length)return null;const Wrapper=modern?ModernSection:Section;return <Wrapper title="Skills"><div className={cn("leading-relaxed",modern&&"space-y-1")}>{modern?data.skills.map((x,i)=><div key={i}>• {x.name}</div>):data.skills.map(x=>x.name+(x.level?` (${x.level})`:"")).join(" · ")}</div></Wrapper>}
function Certifications({data,modern=false}:{data:ResumeInput;modern?:boolean}){if(!data.certifications.length)return null;const Wrapper=modern?ModernSection:Section;return <Wrapper title="Certifications">{data.certifications.map((x,i)=><div className="mb-2" key={i}><b>{x.name}</b><div className="text-black/55">{[x.issuer,x.date].filter(Boolean).join(" · ")}</div></div>)}</Wrapper>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-6"><h2 className="mb-3 border-b border-black/20 pb-1 font-bold uppercase tracking-[.18em] text-forge-700">{title}</h2>{children}</section>}
function ModernSection({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-6"><h2 className="mb-3 bg-black/[.07] px-2 py-1 text-center font-bold uppercase tracking-[.12em]">{title}</h2>{children}</section>}
function Entry({title,subtitle,date,details}:{title:string;subtitle:string;date:string;details:string}){return <div className="mb-4 break-inside-avoid"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{title}</h3><p className="text-black/60">{subtitle}</p></div><span className="shrink-0 text-black/45">{date}</span></div>{details&&<p className="mt-1.5 whitespace-pre-line leading-relaxed">{details}</p>}</div>}
function contact(p:ResumeInput["profile"]){return [p.email,p.phone,p.location,p.website,p.linkedIn].filter((value):value is string=>Boolean(value))}
