"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Award, BookOpen, Briefcase, Check, CircleUserRound, Code2, Eye, FolderKanban, GraduationCap, LayoutTemplate, ListPlus, Loader2, Minus, Palette, Plus, Save, Sparkles, Trash2, Type } from "lucide-react";
import { resumeSchema, type ResumeInput } from "@/lib/validation";
import { Field, TextArea } from "@/components/ui";
import { ResumePreview } from "./resume-preview";
import { PdfButton } from "./pdf-button";
import { cn } from "@/lib/utils";
import { getTemplate, resumeTemplates, type TemplateId } from "@/lib/templates";
import { resumeFonts, type FontId } from "@/lib/fonts";
import { colorThemes, type ColorThemeId } from "@/lib/colors";

const sections=[
  ["templates","Templates",LayoutTemplate],["typography","Typography",Type],["colors","Colors",Palette],["personal","Personal info",CircleUserRound],["summary","Summary",Sparkles],["experience","Experience",Briefcase],["education","Education",GraduationCap],["skills","Skills",Code2],["projects","Projects",FolderKanban],["certifications","Certifications",Award],["additional","Additional content",BookOpen]
] as const;
type Section=typeof sections[number][0];
type RepeatableKey="experiences"|"educations"|"skills"|"projects"|"certifications"|"customSections";

export function ResumeEditor({id,initial}:{id:string;initial:ResumeInput}){
  const [active,setActive]=useState<Section>("templates"); const [status,setStatus]=useState<"idle"|"saving"|"saved"|"error">("idle"); const [message,setMessage]=useState(""); const [zoom,setZoom]=useState(.9);
  const {register,handleSubmit,watch,setValue,formState:{errors}}=useForm<ResumeInput>({resolver:zodResolver(resumeSchema),defaultValues:initial,mode:"onBlur"});
  const data=watch();
  async function save(values:ResumeInput){setStatus("saving");setMessage("");try{const res=await fetch(`/api/resumes/${id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(values)});const json=await res.json();if(!res.ok)throw new Error(json.error);setStatus("saved");setTimeout(()=>setStatus("idle"),2500)}catch(e){setStatus("error");setMessage(e instanceof Error?e.message:"Unable to save")}}
  function add<K extends RepeatableKey>(key:K,value:ResumeInput[K][number]){setValue(key,[...data[key],value] as never,{shouldDirty:true})}
  function remove(key:RepeatableKey,i:number){setValue(key,data[key].filter((_,index)=>index!==i) as never,{shouldDirty:true})}
  return <div className="flex h-[calc(100vh-4.5rem)] min-h-[650px] overflow-hidden bg-[#efeee9]">
    <aside className="hidden w-52 shrink-0 border-r border-black/[.08] bg-white p-3 lg:block"><p className="px-3 pb-3 pt-2 text-[10px] font-bold uppercase tracking-widest text-black/35">Resume sections</p>{sections.map(([key,label,Icon])=><button key={key} onClick={()=>setActive(key)} className={cn("mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium",active===key?"bg-forge-50 text-forge-700":"text-black/55 hover:bg-black/[.03]")}><Icon size={17}/>{label}</button>)}<button type="button" onClick={()=>{setActive("additional");add("customSections",{title:"Custom Section",content:""})}} className="btn-primary mt-4 w-full"><Plus size={16}/>Add content</button></aside>
    <main className="flex min-w-0 flex-1 flex-col bg-white xl:max-w-xl"><div className="flex items-center gap-2 overflow-x-auto border-b border-black/[.07] px-4 py-2 lg:hidden">{sections.map(([key,label,Icon])=><button key={key} title={label} onClick={()=>setActive(key)} className={cn("shrink-0 rounded-lg p-2",active===key?"bg-forge-50 text-forge-700":"text-black/45")}><Icon size={18}/></button>)}</div>
      <form onSubmit={handleSubmit(save,()=>{setStatus("error");setMessage("Please fix the highlighted fields.")})} className="flex min-h-0 flex-1 flex-col"><div className="flex-1 overflow-y-auto px-5 py-7 sm:px-8"><div className="mx-auto max-w-lg"><EditorSection active={active} register={register} errors={errors} data={data} setTemplate={template=>setValue("template",template,{shouldDirty:true})} setFont={font=>setValue("fontFamily",font,{shouldDirty:true})} setColor={color=>setValue("colorTheme",color,{shouldDirty:true})} add={add} remove={remove}/></div></div><div className="flex items-center justify-between border-t border-black/[.07] bg-white px-5 py-3"><span className={cn("text-xs",status==="error"?"text-red-600":"text-black/45")}>{status==="saved"?<span className="flex items-center gap-1"><Check size={14}/>Saved</span>:message}</span><button disabled={status==="saving"} className="btn-primary py-2">{status==="saving"?<Loader2 className="animate-spin" size={16}/>:<Save size={16}/>}Save changes</button></div></form>
    </main>
    <aside className="hidden min-w-0 flex-1 flex-col xl:flex"><div className="flex h-14 items-center justify-between border-b border-black/[.07] bg-white px-5"><div className="flex min-w-0 items-center gap-2"><Eye size={16} className="text-forge-600"/><div className="min-w-0"><div className="text-[10px] font-bold uppercase tracking-wider text-black/35">Live preview</div><div className="truncate text-xs font-semibold">{getTemplate(data.template).name}</div></div></div><div className="flex items-center gap-2"><div className="flex items-center rounded-xl border border-black/10 bg-white p-1"><button type="button" onClick={()=>setZoom(value=>Math.max(.6,+(value-.1).toFixed(1)))} aria-label="Zoom out" className="rounded-lg p-1.5 hover:bg-black/5"><Minus size={14}/></button><span className="w-11 text-center text-[10px] font-semibold text-black/50">{Math.round(zoom*100)}%</span><button type="button" onClick={()=>setZoom(value=>Math.min(1.3,+(value+.1).toFixed(1)))} aria-label="Zoom in" className="rounded-lg p-1.5 hover:bg-black/5"><Plus size={14}/></button></div><PdfButton data={data}/></div></div><div className="flex-1 overflow-auto bg-[radial-gradient(circle_at_center,rgba(47,125,76,.08),transparent_60%)] p-7"><div className="mx-auto transition-[width] duration-200" style={{width:`${zoom*100}%`,maxWidth:`${720*zoom}px`}}><div className="aspect-[1/1.414] overflow-hidden rounded-sm bg-white shadow-[0_20px_60px_rgba(23,33,27,.16)] ring-1 ring-black/5"><ResumePreview data={data} compact/></div></div></div></aside>
  </div>
}

type Props={active:Section;register:ReturnType<typeof useForm<ResumeInput>>["register"];errors:ReturnType<typeof useForm<ResumeInput>>["formState"]["errors"];data:ResumeInput;setTemplate:(template:TemplateId)=>void;setFont:(font:FontId)=>void;setColor:(color:ColorThemeId)=>void;add:<K extends RepeatableKey>(k:K,v:ResumeInput[K][number])=>void;remove:(k:RepeatableKey,i:number)=>void};
function EditorSection({active,register,errors,data,setTemplate,setFont,setColor,add,remove}:Props){
  const title=sections.find(x=>x[0]===active)?.[1];
  const designSection=active==="templates"||active==="typography"||active==="colors";return <><p className="text-xs font-bold uppercase tracking-widest text-forge-700">{designSection?"Design":"Editing"}</p><h1 className="mt-1 font-serif text-3xl font-bold">{title}</h1><p className="mb-7 mt-2 text-sm text-black/50">{active==="templates"?"Choose a layout. Your content stays exactly the same.":active==="typography"?"Choose a readable type style for your resume.":active==="colors"?"Apply a coordinated palette across your resume.":"Keep it clear, specific, and easy to scan."}</p>
    {active==="templates"&&<TemplateChooser data={data} selected={data.template} onSelect={setTemplate}/>}
    {active==="typography"&&<FontChooser selected={data.fontFamily} onSelect={setFont}/>}
    {active==="colors"&&<ColorChooser selected={data.colorTheme} onSelect={setColor}/>}
    {active==="personal"&&<div className="grid gap-4 sm:grid-cols-2"><Field label="Resume title" className="sm:col-span-2" {...register("title")} error={errors.title?.message}/><Field label="Full name *" className="sm:col-span-2" {...register("profile.fullName")} error={errors.profile?.fullName?.message}/><Field label="Email *" type="email" {...register("profile.email")} error={errors.profile?.email?.message}/><Field label="Phone" {...register("profile.phone")}/><Field label="Location" {...register("profile.location")}/><Field label="Website" {...register("profile.website")}/><Field label="LinkedIn" className="sm:col-span-2" {...register("profile.linkedIn")}/></div>}
    {active==="summary"&&<TextArea label="Professional summary" rows={8} placeholder="A concise overview of your strengths, experience, and goals…" {...register("summary")}/>}
    {active==="experience"&&<Repeat items={data.experiences} label="Add experience" onAdd={()=>add("experiences",{company:"",position:"",location:"",startDate:"",endDate:"",current:false,details:""})} onRemove={i=>remove("experiences",i)}>{i=><div className="grid gap-3 sm:grid-cols-2"><Field label="Position *" {...register(`experiences.${i}.position`)} error={errors.experiences?.[i]?.position?.message}/><Field label="Company *" {...register(`experiences.${i}.company`)} error={errors.experiences?.[i]?.company?.message}/><Field label="Location" {...register(`experiences.${i}.location`)}/><Field label="Start date" placeholder="Jan 2023" {...register(`experiences.${i}.startDate`)}/><Field label="End date" placeholder="Present" {...register(`experiences.${i}.endDate`)}/><label className="flex items-end gap-2 pb-3 text-sm"><input type="checkbox" {...register(`experiences.${i}.current`)}/>Currently work here</label><TextArea className="sm:col-span-2" label="Highlights" placeholder="Describe impact and results…" {...register(`experiences.${i}.details`)}/></div>}</Repeat>}
    {active==="education"&&<Repeat items={data.educations} label="Add education" onAdd={()=>add("educations",{school:"",degree:"",field:"",startDate:"",endDate:"",details:""})} onRemove={i=>remove("educations",i)}>{i=><div className="grid gap-3 sm:grid-cols-2"><Field label="School *" {...register(`educations.${i}.school`)} error={errors.educations?.[i]?.school?.message}/><Field label="Degree *" {...register(`educations.${i}.degree`)} error={errors.educations?.[i]?.degree?.message}/><Field label="Field of study" {...register(`educations.${i}.field`)}/><Field label="Start date" {...register(`educations.${i}.startDate`)}/><Field label="End date" {...register(`educations.${i}.endDate`)}/><TextArea className="sm:col-span-2" label="Details" {...register(`educations.${i}.details`)}/></div>}</Repeat>}
    {active==="skills"&&<Repeat items={data.skills} label="Add skill" onAdd={()=>add("skills",{name:"",level:""})} onRemove={i=>remove("skills",i)}>{i=><div className="grid gap-3 sm:grid-cols-2"><Field label="Skill *" {...register(`skills.${i}.name`)} error={errors.skills?.[i]?.name?.message}/><Field label="Level" placeholder="Advanced" {...register(`skills.${i}.level`)}/></div>}</Repeat>}
    {active==="projects"&&<Repeat items={data.projects} label="Add project" onAdd={()=>add("projects",{name:"",description:"",url:"",technologies:""})} onRemove={i=>remove("projects",i)}>{i=><div className="grid gap-3 sm:grid-cols-2"><Field label="Project name *" {...register(`projects.${i}.name`)} error={errors.projects?.[i]?.name?.message}/><Field label="URL" {...register(`projects.${i}.url`)}/><Field className="sm:col-span-2" label="Technologies" {...register(`projects.${i}.technologies`)}/><TextArea className="sm:col-span-2" label="Description" {...register(`projects.${i}.description`)}/></div>}</Repeat>}
    {active==="certifications"&&<Repeat items={data.certifications} label="Add certification" onAdd={()=>add("certifications",{name:"",issuer:"",date:"",url:""})} onRemove={i=>remove("certifications",i)}>{i=><div className="grid gap-3 sm:grid-cols-2"><Field label="Certification *" {...register(`certifications.${i}.name`)} error={errors.certifications?.[i]?.name?.message}/><Field label="Issuer" {...register(`certifications.${i}.issuer`)}/><Field label="Date" {...register(`certifications.${i}.date`)}/><Field label="Credential URL" {...register(`certifications.${i}.url`)}/></div>}</Repeat>}
    {active==="additional"&&<div className="space-y-5"><ContentPresets onAdd={title=>add("customSections",{title,content:""})}/><Repeat items={data.customSections} label="Add custom section" onAdd={()=>add("customSections",{title:"Custom Section",content:""})} onRemove={i=>remove("customSections",i)}>{i=><div className="space-y-3"><Field label="Section title *" {...register(`customSections.${i}.title`)} error={errors.customSections?.[i]?.title?.message}/><TextArea label="Content" placeholder="Add each item on a new line…" {...register(`customSections.${i}.content`)}/></div>}</Repeat></div>}
  </>;
}
function Repeat<T>({items,label,onAdd,onRemove,children}:{items:T[];label:string;onAdd:()=>void;onRemove:(i:number)=>void;children:(i:number)=>React.ReactNode}){return <div className="space-y-4">{items.map((_,i)=><div className="card relative p-4" key={i}><button type="button" onClick={()=>onRemove(i)} aria-label="Remove item" className="absolute right-3 top-3 z-10 rounded-lg p-2 text-black/35 hover:bg-red-50 hover:text-red-600"><Trash2 size={16}/></button><div className="pr-8">{children(i)}</div></div>)}<button type="button" onClick={onAdd} className="btn-secondary w-full border-dashed"><Plus size={16}/>{label}</button></div>}

function TemplateChooser({data,selected,onSelect}:{data:ResumeInput;selected:TemplateId;onSelect:(template:TemplateId)=>void}){return <div className="grid gap-5 sm:grid-cols-2">{resumeTemplates.map(template=><TemplateCard key={template.id} name={template.name} description={template.description} selected={selected===template.id} onClick={()=>onSelect(template.id)}><div className="h-full w-full origin-top-left scale-50"><div className="min-h-[200%] w-[200%]"><ResumePreview data={templatePreviewData(data,template.id)} compact/></div></div></TemplateCard>)}</div>}
function TemplateCard({name,description,selected,onClick,children}:{name:string;description:string;selected:boolean;onClick:()=>void;children:React.ReactNode}){return <button type="button" aria-pressed={selected} onClick={onClick} className={cn("overflow-hidden rounded-2xl border-2 bg-white text-left transition hover:-translate-y-0.5 hover:shadow-soft",selected?"border-forge-600 ring-4 ring-forge-500/10":"border-black/10")}><div className="aspect-[1/1.414] overflow-hidden bg-[#e8e8e5] p-3"><div className="h-full overflow-hidden bg-white shadow-sm">{children}</div></div><div className="flex items-start justify-between border-t border-black/[.07] p-4"><div><div className="font-bold">{name}</div><p className="mt-1 text-xs leading-5 text-black/50">{description}</p></div>{selected&&<span className="grid size-6 shrink-0 place-items-center rounded-full bg-forge-600 text-white"><Check size={14}/></span>}</div></button>}
function templatePreviewData(data:ResumeInput,template:TemplateId):ResumeInput{return {...data,template,summary:data.summary||"Product-minded professional known for clear thinking, thoughtful execution, and measurable results.",profile:{fullName:data.profile.fullName||"Jordan Lee",email:data.profile.email||"jordan@example.com",phone:data.profile.phone||"+1 555 012 3456",location:data.profile.location||"New York, NY",website:data.profile.website,linkedIn:data.profile.linkedIn||"linkedin.com/in/jordanlee"},experiences:data.experiences.length?data.experiences:[{position:"Senior Product Designer",company:"Northstar Studio",location:"New York, NY",startDate:"2022",endDate:"",current:true,details:"Led cross-functional product work from discovery through launch.\nImproved key customer workflows through research and iteration."},{position:"Product Designer",company:"Atlas Labs",location:"Remote",startDate:"2019",endDate:"2022",current:false,details:"Built accessible experiences and a reusable design system."}],educations:data.educations.length?data.educations:[{school:"State University",degree:"Bachelor of Arts",field:"Design",startDate:"2015",endDate:"2019",details:""}],skills:data.skills.length?data.skills:["Product strategy","User research","Design systems","Prototyping","Collaboration"].map(name=>({name,level:""})),projects:data.projects,certifications:data.certifications}}
function FontChooser({selected,onSelect}:{selected:FontId;onSelect:(font:FontId)=>void}){return <div className="space-y-3">{resumeFonts.map(font=><button type="button" key={font.id} onClick={()=>onSelect(font.id)} className={cn("flex w-full items-center justify-between rounded-2xl border-2 bg-white p-5 text-left transition hover:border-forge-500/50",selected===font.id?"border-forge-600 ring-4 ring-forge-500/10":"border-black/10")}><div><div className="text-2xl" style={{fontFamily:font.css}}>Aa Better work starts here.</div><div className="mt-2 font-semibold">{font.name}</div><p className="mt-1 text-xs text-black/50">{font.description}</p></div>{selected&&<span className="grid size-6 shrink-0 place-items-center rounded-full bg-forge-600 text-white"><Check size={14}/></span>}</button>)}</div>}
function ContentPresets({onAdd}:{onAdd:(title:string)=>void}){return <div><p className="label">Quick add</p><div className="grid grid-cols-2 gap-2">{["Languages","Awards","Volunteer Work","Interests","Publications","References"].map(title=><button type="button" key={title} onClick={()=>onAdd(title)} className="btn-secondary justify-start"><ListPlus size={15}/>{title}</button>)}</div></div>}
function ColorChooser({selected,onSelect}:{selected:ColorThemeId;onSelect:(color:ColorThemeId)=>void}){return <div className="grid grid-cols-2 gap-3">{colorThemes.map(theme=><button type="button" key={theme.id} onClick={()=>onSelect(theme.id)} className={cn("flex items-center gap-3 rounded-2xl border-2 bg-white p-4 text-left transition hover:border-forge-500/50",selected===theme.id?"border-forge-600 ring-4 ring-forge-500/10":"border-black/10")}><span className="grid size-10 shrink-0 place-items-center overflow-hidden rounded-full ring-1 ring-black/10" style={theme.id==="template"?{background:"conic-gradient(#24643c,#315f7d,#6d315d,#a14f38,#24643c)"}:{backgroundColor:theme.accent}}>{selected===theme.id&&<Check size={16} className="text-white"/>}</span><span className="text-sm font-semibold">{theme.name}</span></button>)}</div>}
