"use client";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { ResumeInput } from "@/lib/validation";

const s=StyleSheet.create({page:{padding:40,fontFamily:"Helvetica",fontSize:9,color:"#202521"},modernPage:{padding:0,fontFamily:"Helvetica",fontSize:8.5,color:"#202521",flexDirection:"row"},sidebar:{width:"36%",height:"100%",backgroundColor:"#e4e8e4",padding:28},main:{width:"64%",padding:32},name:{fontSize:25,fontFamily:"Helvetica-Bold",marginBottom:6},modernName:{fontSize:20,fontFamily:"Helvetica-Bold",textTransform:"uppercase",lineHeight:1.1,marginBottom:14},contact:{color:"#666",marginBottom:14},contactItem:{color:"#555",marginBottom:5},section:{marginTop:13},heading:{fontSize:9,fontFamily:"Helvetica-Bold",textTransform:"uppercase",letterSpacing:1.5,color:"#24643c",borderBottom:"1 solid #ddd",paddingBottom:3,marginBottom:7},modernHeading:{fontSize:8.5,fontFamily:"Helvetica-Bold",textTransform:"uppercase",letterSpacing:1,backgroundColor:"#d3d7d3",textAlign:"center",padding:4,marginBottom:7},row:{flexDirection:"row",justifyContent:"space-between",gap:8},bold:{fontFamily:"Helvetica-Bold"},muted:{color:"#666"},details:{marginTop:3,lineHeight:1.4},entry:{marginBottom:9},skill:{marginBottom:4}});

export function ResumePdf({data}:{data:ResumeInput}){return <Document title={data.title}>{data.template==="modern"?<ModernPdf data={data}/>:<ClassicPdf data={data}/>}</Document>}
function ClassicPdf({data}:{data:ResumeInput}){const p=data.profile;return <Page size="A4" style={s.page}><Text style={s.name}>{p.fullName||"Your Name"}</Text><Text style={s.contact}>{contacts(p).join("  ·  ")}</Text>{data.summary&&<PdfSection title="Professional Summary"><Text style={s.details}>{data.summary}</Text></PdfSection>}<PdfMain data={data}/>{data.skills.length>0&&<PdfSection title="Skills"><Text>{data.skills.map(x=>x.name).join("  ·  ")}</Text></PdfSection>}<PdfCertifications data={data}/></Page>}
function ModernPdf({data}:{data:ResumeInput}){const p=data.profile;return <Page size="A4" style={s.modernPage}><View style={s.sidebar}><Text style={s.modernName}>{p.fullName||"Your Name"}</Text>{contacts(p).map((x,i)=><Text key={i} style={s.contactItem}>{x}</Text>)}{data.summary&&<PdfSection title="Summary" modern><Text style={s.details}>{data.summary}</Text></PdfSection>}{data.skills.length>0&&<PdfSection title="Skills" modern>{data.skills.map((x,i)=><Text key={i} style={s.skill}>• {x.name}</Text>)}</PdfSection>}<PdfCertifications data={data} modern/></View><View style={s.main}><PdfMain data={data} modern/></View></Page>}
function PdfMain({data,modern=false}:{data:ResumeInput;modern?:boolean}){return <>{data.experiences.length>0&&<PdfSection title="Professional Experience" modern={modern}>{data.experiences.map((x,i)=><PdfEntry key={i} title={x.position} sub={`${x.company}${x.location?` · ${x.location}`:""}`} date={`${x.startDate} — ${x.current?"Present":x.endDate}`} details={x.details}/>)}</PdfSection>}{data.educations.length>0&&<PdfSection title="Education" modern={modern}>{data.educations.map((x,i)=><PdfEntry key={i} title={x.degree+(x.field?` in ${x.field}`:"")} sub={x.school} date={`${x.startDate} — ${x.endDate}`} details={x.details}/>)}</PdfSection>}{data.projects.length>0&&<PdfSection title="Projects" modern={modern}>{data.projects.map((x,i)=><PdfEntry key={i} title={x.name} sub={x.technologies} date="" details={x.description}/>)}</PdfSection>}</>}
function PdfCertifications({data,modern=false}:{data:ResumeInput;modern?:boolean}){return data.certifications.length>0?<PdfSection title="Certifications" modern={modern}>{data.certifications.map((x,i)=><Text key={i} style={s.skill}>{x.name} — {[x.issuer,x.date].filter(Boolean).join(", ")}</Text>)}</PdfSection>:null}
function PdfSection({title,children,modern=false}:{title:string;children:React.ReactNode;modern?:boolean}){return <View style={s.section}><Text style={modern?s.modernHeading:s.heading}>{title}</Text>{children}</View>}
function PdfEntry({title,sub,date,details}:{title:string;sub:string;date:string;details:string}){return <View style={s.entry} wrap={false}><View style={s.row}><Text style={s.bold}>{title}</Text><Text style={s.muted}>{date}</Text></View><Text style={s.muted}>{sub}</Text>{details&&<Text style={s.details}>{details}</Text>}</View>}
function contacts(p:ResumeInput["profile"]){return [p.email,p.phone,p.location,p.website,p.linkedIn].filter((value):value is string=>Boolean(value))}
