import type { ResumeInput } from "@/lib/validation";
import { cn } from "@/lib/utils";
import { getTemplate, type ResumeTemplate } from "@/lib/templates";

export function ResumePreview({ data, compact=false }: { data:ResumeInput; compact?:boolean }) {const template=getTemplate(data.template);return template.layout==="split"?<SplitPreview data={data} compact={compact} template={template}/>:<SinglePreview data={data} compact={compact} template={template}/>}

function SinglePreview({data,compact,template}:{data:ResumeInput;compact:boolean;template:ResumeTemplate}){const p=data.profile;const dense=template.density==="compact";return <div className={cn("min-h-full bg-white text-[#202521]",compact?dense?"p-6 text-[7px]":"p-8 text-[8px]":dense?"p-[5%] text-[10px]":"p-[7%] text-[11px]")}><header className={cn("pb-4",template.header==="line"&&"border-b-2",template.header==="centered"&&"border-b text-center",template.header==="band"&&cn("-mx-8 -mt-8 mb-5 p-8 text-white",dense&&"-mx-6 -mt-6 p-6"))} style={{borderColor:template.accent,backgroundColor:template.header==="band"?template.accent:undefined}}><h1 className={cn("font-serif font-bold",compact?"text-2xl":"text-4xl",template.id==="mono"&&"font-mono uppercase tracking-tight")}>{p.fullName||"Your Name"}</h1><div className={cn("mt-2 flex flex-wrap gap-x-3",template.header==="centered"&&"justify-center",template.header==="band"?"text-white/75":"text-black/55")}>{contact(p).map((x,i)=><span key={i}>{x}</span>)}</div></header>{data.summary&&<Section title="Professional Summary" template={template}><p className="whitespace-pre-line leading-relaxed">{data.summary}</p></Section>}<MainSections data={data} template={template}/><div className="grid grid-cols-2 gap-8"><Skills data={data} template={template}/><Certifications data={data} template={template}/></div></div>}

function SplitPreview({data,compact,template}:{data:ResumeInput;compact:boolean;template:ResumeTemplate}){const p=data.profile;const inverse=template.id==="creative";const dense=template.density==="compact";return <div className={cn("grid min-h-full grid-cols-[36%_64%] bg-white text-[#202521]",compact?dense?"text-[7px]":"text-[8px]":"text-[11px]")}><aside className={cn(compact?"p-6":"p-[12%]",inverse&&"text-white")} style={{backgroundColor:template.panel}}><h1 className={cn("font-serif font-bold uppercase leading-tight",compact?"text-xl":"text-3xl")}>{p.fullName||"Your Name"}</h1><div className={cn("mt-5 space-y-2 break-words",inverse?"text-white/70":"text-black/65")}>{contact(p).map((x,i)=><div key={i}>{x}</div>)}</div>{data.summary&&<Section title="Summary" template={template} inverse={inverse}><p className="whitespace-pre-line leading-relaxed">{data.summary}</p></Section>}<Skills data={data} template={template} inverse={inverse}/><Certifications data={data} template={template} inverse={inverse}/></aside><main className={cn(compact?dense?"p-5":"p-7":"p-[8%]")}><MainSections data={data} template={template}/></main></div>}

function MainSections({data,template}:{data:ResumeInput;template:ResumeTemplate}){return <>{!!data.experiences.length&&<Section title="Professional Experience" template={template}>{data.experiences.map((x,i)=><Entry key={i} title={x.position} subtitle={x.company+(x.location?` · ${x.location}`:"")} date={`${x.startDate}${x.startDate||x.endDate?" — ":""}${x.current?"Present":x.endDate}`} details={x.details} dense={template.density==="compact"}/>)}</Section>}{!!data.educations.length&&<Section title="Education" template={template}>{data.educations.map((x,i)=><Entry key={i} title={x.degree+(x.field?` in ${x.field}`:"")} subtitle={x.school} date={`${x.startDate}${x.startDate||x.endDate?" — ":""}${x.endDate}`} details={x.details} dense={template.density==="compact"}/>)}</Section>}{!!data.projects.length&&<Section title="Projects" template={template}>{data.projects.map((x,i)=><Entry key={i} title={x.name} subtitle={x.technologies} date={x.url} details={x.description} dense={template.density==="compact"}/>)}</Section>}</>}
function Skills({data,template,inverse=false}:{data:ResumeInput;template:ResumeTemplate;inverse?:boolean}){if(!data.skills.length)return null;return <Section title="Skills" template={template} inverse={inverse}><div className={cn("leading-relaxed",template.layout==="split"&&"space-y-1")}>{template.layout==="split"?data.skills.map((x,i)=><div key={i}>• {x.name}</div>):data.skills.map(x=>x.name+(x.level?` (${x.level})`:"")).join(" · ")}</div></Section>}
function Certifications({data,template,inverse=false}:{data:ResumeInput;template:ResumeTemplate;inverse?:boolean}){if(!data.certifications.length)return null;return <Section title="Certifications" template={template} inverse={inverse}>{data.certifications.map((x,i)=><div className="mb-2" key={i}><b>{x.name}</b><div className={inverse?"text-white/65":"text-black/55"}>{[x.issuer,x.date].filter(Boolean).join(" · ")}</div></div>)}</Section>}
function Section({title,template,inverse=false,children}:{title:string;template:ResumeTemplate;inverse?:boolean;children:React.ReactNode}){return <section className={template.density==="compact"?"mt-4":"mt-6"}><h2 className={cn("mb-3 font-bold uppercase tracking-[.14em]",template.headings==="line"&&"border-b pb-1",template.headings==="bar"&&"px-2 py-1 text-center",template.headings==="caps"&&"tracking-[.2em]")} style={{color:inverse?"white":template.accent,borderColor:inverse?"rgba(255,255,255,.4)":template.accent,backgroundColor:template.headings==="bar"?(inverse?"rgba(255,255,255,.14)":`${template.accent}14`):undefined}}>{title}</h2>{children}</section>}
function Entry({title,subtitle,date,details,dense}:{title:string;subtitle:string;date:string;details:string;dense:boolean}){return <div className={cn("break-inside-avoid",dense?"mb-2.5":"mb-4")}><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold">{title}</h3><p className="text-black/60">{subtitle}</p></div><span className="shrink-0 text-black/45">{date}</span></div>{details&&<p className="mt-1.5 whitespace-pre-line leading-relaxed">{details}</p>}</div>}
function contact(p:ResumeInput["profile"]){return [p.email,p.phone,p.location,p.website,p.linkedIn].filter((value):value is string=>Boolean(value))}
