"use client";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { ResumeInput } from "@/lib/validation";
import { getTemplate, type ResumeTemplate } from "@/lib/templates";

const s=StyleSheet.create({page:{padding:40,fontFamily:"Helvetica",fontSize:9,color:"#202521"},splitPage:{padding:0,fontFamily:"Helvetica",fontSize:8.5,color:"#202521",flexDirection:"row"},sidebar:{width:"36%",height:"100%",padding:28},main:{width:"64%",padding:32},header:{paddingBottom:12},bandHeader:{marginTop:-40,marginLeft:-40,marginRight:-40,paddingTop:30,paddingBottom:20,paddingHorizontal:40,marginBottom:10},name:{fontSize:25,fontFamily:"Helvetica-Bold",marginBottom:6},splitName:{fontSize:20,fontFamily:"Helvetica-Bold",textTransform:"uppercase",lineHeight:1.1,marginBottom:14},contact:{color:"#666",marginBottom:4},section:{marginTop:13},heading:{fontSize:9,fontFamily:"Helvetica-Bold",textTransform:"uppercase",letterSpacing:1.2,paddingBottom:3,marginBottom:7},barHeading:{fontSize:8.5,fontFamily:"Helvetica-Bold",textTransform:"uppercase",letterSpacing:1,textAlign:"center",padding:4,marginBottom:7},row:{flexDirection:"row",justifyContent:"space-between",gap:8},bold:{fontFamily:"Helvetica-Bold"},muted:{color:"#666"},details:{marginTop:3,lineHeight:1.4},entry:{marginBottom:9},entryCompact:{marginBottom:6},skill:{marginBottom:4}});

export function ResumePdf({data}:{data:ResumeInput}){const template=getTemplate(data.template);return <Document title={data.title}>{template.layout==="split"?<SplitPdf data={data} template={template}/>:<SinglePdf data={data} template={template}/>}</Document>}

function SinglePdf({data,template}:{data:ResumeInput;template:ResumeTemplate}){const p=data.profile;const band=template.header==="band";return <Page size="A4" style={[s.page,template.density==="compact"?{fontSize:8,padding:32}:{}]}><View style={[s.header,band?s.bandHeader:{},template.header==="line"?{borderBottomWidth:2,borderBottomColor:template.accent}:{},template.header==="centered"?{textAlign:"center",borderBottomWidth:1,borderBottomColor:template.accent}:{},band?{backgroundColor:template.accent,color:"#ffffff"}:{}]}><Text style={[s.name,template.id==="mono"?{fontFamily:"Courier-Bold",textTransform:"uppercase"}:{}]}>{p.fullName||"Your Name"}</Text><Text style={[s.contact,band?{color:"#dce7ed"}:{}]}>{contacts(p).join("  ·  ")}</Text></View>{data.summary&&<PdfSection title="Professional Summary" template={template}><Text style={s.details}>{data.summary}</Text></PdfSection>}<PdfMain data={data} template={template}/>{data.skills.length>0&&<PdfSection title="Skills" template={template}><Text>{data.skills.map(x=>x.name).join("  ·  ")}</Text></PdfSection>}<PdfCertifications data={data} template={template}/></Page>}

function SplitPdf({data,template}:{data:ResumeInput;template:ResumeTemplate}){const p=data.profile;const inverse=template.id==="creative";return <Page size="A4" style={s.splitPage}><View style={[s.sidebar,{backgroundColor:template.panel,color:inverse?"#ffffff":"#202521"}]}><Text style={s.splitName}>{p.fullName||"Your Name"}</Text>{contacts(p).map((x,i)=><Text key={i} style={[s.contact,{color:inverse?"#d9e4ea":"#555555"}]}>{x}</Text>)}{data.summary&&<PdfSection title="Summary" template={template} inverse={inverse}><Text style={s.details}>{data.summary}</Text></PdfSection>}{data.skills.length>0&&<PdfSection title="Skills" template={template} inverse={inverse}>{data.skills.map((x,i)=><Text key={i} style={s.skill}>• {x.name}</Text>)}</PdfSection>}<PdfCertifications data={data} template={template} inverse={inverse}/></View><View style={s.main}><PdfMain data={data} template={template}/></View></Page>}

function PdfMain({data,template}:{data:ResumeInput;template:ResumeTemplate}){return <>{data.experiences.length>0&&<PdfSection title="Professional Experience" template={template}>{data.experiences.map((x,i)=><PdfEntry key={i} title={x.position} sub={`${x.company}${x.location?` · ${x.location}`:""}`} date={`${x.startDate} — ${x.current?"Present":x.endDate}`} details={x.details} compact={template.density==="compact"}/>)}</PdfSection>}{data.educations.length>0&&<PdfSection title="Education" template={template}>{data.educations.map((x,i)=><PdfEntry key={i} title={x.degree+(x.field?` in ${x.field}`:"")} sub={x.school} date={`${x.startDate} — ${x.endDate}`} details={x.details} compact={template.density==="compact"}/>)}</PdfSection>}{data.projects.length>0&&<PdfSection title="Projects" template={template}>{data.projects.map((x,i)=><PdfEntry key={i} title={x.name} sub={x.technologies} date="" details={x.description} compact={template.density==="compact"}/>)}</PdfSection>}</>}
function PdfCertifications({data,template,inverse=false}:{data:ResumeInput;template:ResumeTemplate;inverse?:boolean}){return data.certifications.length>0?<PdfSection title="Certifications" template={template} inverse={inverse}>{data.certifications.map((x,i)=><Text key={i} style={s.skill}>{x.name} — {[x.issuer,x.date].filter(Boolean).join(", ")}</Text>)}</PdfSection>:null}
function PdfSection({title,children,template,inverse=false}:{title:string;children:React.ReactNode;template:ResumeTemplate;inverse?:boolean}){const line=template.headings==="line";const bar=template.headings==="bar";return <View style={s.section}><Text style={[bar?s.barHeading:s.heading,{color:inverse?"#ffffff":template.accent},line?{borderBottomWidth:1,borderBottomColor:inverse?"#ffffff":template.accent}:{},bar?{backgroundColor:inverse?"#ffffff22":`${template.accent}18`}:{}]}>{title}</Text>{children}</View>}
function PdfEntry({title,sub,date,details,compact}:{title:string;sub:string;date:string;details:string;compact:boolean}){return <View style={compact?s.entryCompact:s.entry} wrap={false}><View style={s.row}><Text style={s.bold}>{title}</Text><Text style={s.muted}>{date}</Text></View><Text style={s.muted}>{sub}</Text>{details&&<Text style={s.details}>{details}</Text>}</View>}
function contacts(p:ResumeInput["profile"]){return [p.email,p.phone,p.location,p.website,p.linkedIn].filter((value):value is string=>Boolean(value))}
